### ISSUE TITLE
32bit is deprecated on newer Mac OS versions?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [concurrency/kroc#17]
Attempting to build on:

```
System Version:	macOS 10.15.3 (19D49f)
Kernel Version:	Darwin 19.3.0
```

leads to this error:
`ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)`

which is I believe due to deprecation of 32bit builds on newer Mac OS (Xcode?) versions.

I'd be willing to try some fixes (I will play with ARCHS setting of Xcode), but I suspect the problem will be *a lot* deeper and beyond my knowledge. But if you have any pointers for things I could try, please comment them here, I'm an old Occam fan and would love to see it running on my Mac and try my hand at writing some again, after a 35y break since I tried it at University. :-)

**Comment by jadudm** [comment]
Hi Andrew,

I'm certain there will be learning involved for me as well, but I'll join you on the journey. 

One path that might be easier is to use the Transterpreter backend to start. It was written in ANSI C (of some variant... possibly 99?), and shouldn't have build issues. 

I'm happy to communicate here, via email, or we can do a live chat at some point to talk through some strategies, and report out so that anyone else following along is in the loop.

(I am worried that the compiler itself may be a problem. I've wondered for some time whether we should wrap the compiler in a 32-bit Docker image, and just freeze it for all time. That might be the solution to at least that part of the toolchain...)

**Comment by andrewdavidmackenzie** [comment]
I re-read some of the linked docs. Should I be using the `llvm` branch to try to build it on Mac OS X?

Any thought of trying to merge "the latest and greatest" to master branch, there are quite a few branches there I see and not sure what is what.

BTW: a possible first action would be to update docs to be more self-contained, with some updated build and install docs for different OS. I have access to Mac OS X and Linux and could try to help with that.

**Comment by jadudm** [comment]
I spent some time this morning (EST) looking at things.

I'm unsure how deep we'll need to go. Or, I'm concerned re: how much the world has moved forward since the project was last actively developed. 

1. There's a lot of warnings throughout the compiler codebase that may, or may not, be safe to ignore. 'occ21' is a compiler that goes back to the 80's; the world was, and would always be, 32-bit. Now that we live in a 64-bit world, it may be that a move from all of the `(void *)` casts that were common at the time may be necessary.

2. Adam last touched 'master' 3 years ago. I would trust that branch. Everything else could probably be safely dropped... but, I'm not going to do that casually at this moment in time. 

3. There's a question about what should and should not be kept in a build tree, as far as I'm concerned. Smart pruning could make this an easier project.

What I mean by bullet 3 is that there are things in the build that, perhaps, can be set aside for a moment. For example, there were a number of foreign libraries that can probably be set aside initially that will (I expect) fail in surprising/unsurprising ways. 

I'll either reply here, or use another Github mechanism to make some notes along this line.

**Comment by jadudm** [comment]
In this fork/branch:

https://github.com/jadudm/kroc/tree/build-20200327

I can do the following from the root of the checkout (in that branch):

```
./build --prefix=<local prefix> --with-toolchain=tvm --with-wrapper=posix
```

and get a build on Mac and Linux.

"get a build" means "something that builds, but does not run."

That is, I do get `occ21` and `tvm`, but running the bytecode that gets generated from a valid occam program yields a segfault. Under valgrind, this ... could be a number of things. (In theory, the TVM is getting into its execution cycle, but I cannot tell if it is trying to execute good or bad bytecode yet.) If I compile with DEBUG enabled, then I should be able to figure out if we're generating bad bytecode, or if the TVM has problems under 64-bit (which it shouldn't). 

I am going to close this thread, because I believe this solves the "build" question, but there are now others, which should become their own tickets.

I'm not sure where the best place to work is. We could just work against this repository. That is, if I can get something working in my branch, I'll merge it into master there, and then merge it back here. But, I'm open to working with whatever workflow makes the most sense for... two people?

**Comment by andrewdavidmackenzie** [comment]
OK, I'll give that version a whirl, just to see.

It would be great if you could merge back in  those fixes. Even the build fixes initially are a start - even if it doesn't run yet.

Feel free to close this then.

**Comment by jadudm** [comment]
Merged into concurrency/kroc, and closing this ticket.
